package com.partyapp_admin.utils

const val LOGIN = "login"
const val SIGNUP = "signup"
const val HOME = "home"
const val FORGOT = "forgot"
const val SPLASH = "splash"
const val ORDERS = "Orders"
const val ROOT = "root"
const val CONTENT = "content"
const val AUTHENTICATION = "authentication"
const val DETAILS = "details"
const val ADMIN = "admins"
const val PRODUCTS = "products"
const val WHISKY = "whisky"
const val CARBONATED= "carbonated"
const val CATEGORY= "category"
const val NAME= "name"
const val SEARCH_PRODUCT = "searchProduct"
const val ADD_PRODUCT= "addProduct"
